[package]
name = "convention-notify"
version = "0.1.0"
authors = ["Matrix <113445886@qq.com>"]

[dependencies]
chrono = "0.4"
dayu = "0.2"
libxml = "0.1"
regex = "0.2"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
url = "1.7"
